[package]
name = "frajd-o-matic"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
poise = "0.6.1"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

dice = { workspace = true }
discord = { workspace = true }
